title: NoLoJS - Reduce the JS Workload with no- or lo-JS options.
description: An organic collection of common JS patterns that can be replaced with just HTML, CSS, and no, or very low, JS.
markdown: kramdown
highlighter: rouge
collections:
  scripts:
    output: true
